name: Servlet CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.0
        env:
          MYSQL_DATABASE: comp_3940
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Install AWS Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Compile Java Servlet
        run: |
          mkdir -p build/classes
          CLASSPATH=$(find WEB-INF/lib -name "*.jar" | tr '\n' ':')
          javac -d build/classes -classpath "$CLASSPATH" WEB-INF/classes/*.java
          
          
      - name: Package into WAR file
        run: |
          mkdir -p build/webapp/WEB-INF/classes
          cp -r build/classes/* build/webapp/WEB-INF/classes
          cp -r WEB-INF/lib build/webapp/WEB-INF/
          cp -r WEB-INF/web.xml build/webapp/WEB-INF/ 
          cd build && jar -cvf quizapp.war -C webapp .

      - name: Upload WAR file (just for checking)
        uses: actions/upload-artifact@v4
        with:
          name: quizapp-war
          path: build/quizapp.war

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
  
      - name: Initialize Elastic Beanstalk
        run: |
          if ! eb list | grep -q "quizApp"; then
            eb init quizApp --platform "Tomcat 10 with Corretto 21 running on 64bit Amazon Linux 2023" --region us-west-2
            eb create quizApp-dev || echo "Environment already exists"
          fi
          eb use quizApp-dev

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy