name: Servlet CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Compile Java Servlet
        run: |
          mkdir -p build/classes
          # Create a classpath variable with all JARs in lib
          CLASSPATH=$(find WEB-INF/lib -name "*.jar" | tr '\n' ':')
          # Compile all .java files in classes
          javac -d build/classes -classpath "$CLASSPATH" WEB-INF/classes/*.java
          
          
      - name: Package into WAR
        run: |
          mkdir -p build/webapp/WEB-INF/classes
          cp -r build/classes/* build/webapp/WEB-INF/classes
          cp -r WEB-INF/lib build/webapp/WEB-INF/
          cp -r WEB-INF/web.xml build/webapp/WEB-INF/ 
          cd build && jar -cvf myapp.war -C webapp .
